[package]
name = "cs2d-stats-parser"
version = "3.0.1"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.40"
clap = "4.5.35"
csv = "1.3.1"
notify = "8.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
